### ISSUE TITLE
String literals containing "require" or "define" will be replaced

### ISSUE THREAD

**Issue by jrowlingson** [Esri/ember-cli-amd#19]
String literals containing the either "require" or "define" will be replaced with the pig latin version. This was first noticed after our ember-i18n `locales\en\translation.js` file was altered.

**Comment by odoe** [comment]
I'm going to have to spend some more time on this one. A simple regex fix won't cut it, because we need to pig latin the declarations as well.

ember-cli loader has a [noConflict](https://github.com/ember-cli/loader.js#no-conflict) method, but there's no real direction on how to use it. The link they provide does not use that method, it does something else. It may not work 100% either for our use case. I'll keep digging.

**Comment by mjuniper** [comment]
We're running into this issue too. We are seeing it in our ember-intl translations.

**Comment by ffaubry** [comment]
Fixed in release 1.0.0
