### ISSUE TITLE
Document how to use with locally hosted version of ArcGIS libs

### ISSUE THREAD

**Issue by JaronA** [Esri/ember-cli-amd#23]
Hi,

I'm wondering if it'd be possible to add documentation on how to use the plugin while having a copy of the ArcGIS APIs locally hosted.

The APIs can be downloaded here. I'm hoping for guidance as to how to correctly integrate it with a Ember CLI build.
https://developers.arcgis.com/downloads/

Jaron

**Comment by JaronA** [comment]
I've managed to get it mostly working but I'm not experiencing errors that looks like:
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:4200/arcgis/dojox/gfx/filters.js 
Error: scriptError(…)(anonymous function) @ init.js:31
src: dojoLoader
info: Array[2]

If I include dojox/gfx/filters.js  as part of the build the error goes away. However, I only have to do this for a small subset the arcgis files so I'm thinking I'm doing something else wrong. Any ideas?

**Comment by odoe** [comment]
I can put something together, but as of right now it's not the recommended way of using the addon. The steps are similar to what you would do [here for the bower release](https://github.com/Esri/jsapi-resources/tree/master/bower/requirejs) to build with r.js. This process hasn't been fully tested since we first wrote the addon, so may not work exactly anymore.

The current recommended workflow is:
1. Use the CDN version of API for development.
2. Create a custom build with [Bower release](https://github.com/Esri/arcgis-js-api) and replace CDN URL with built URL.
3. Or use the [web optimizer](http://jso.arcgis.com/) and replace the CDN with hosted custom build URL.

I'll test further, thanks!

**Comment by JaronA** [comment]
Any updates on how your testing went?

**Comment by odoe** [comment]
I had a solution working, but there's actually a couple of different ways to do it that might get integrated into the addon itself. I'm an Ember conference this week and when I get back will talk to the person that has a current workflow I think is well suited for the addon.

Thanks!

**Comment by JaronA** [comment]
Thanks for the quick update :)
Enjoy the conference, wish I was there!

**Comment by JaronAndre** [comment]
Any updates on this issue?

**Comment by odoe** [comment]
There's no easy way to do this because of how Ember copies and serves files.
Minor success in having a script that creates a symlink to the source in the output temp directory used by `ember serve`, but it's a bit cumbersome.

My suggestion is to stick with the CDN use, use the output dependency text file to create a bower build and include that with a released version if needed. But during development time, it's not an easy task to accomplish.

**Comment by JaronAndre** [comment]
Alright, thanks for the advice

**Comment by stdavis** [comment]
Is this still valid? No good way to use local versions of `esri` & `dojo`? The example in the readme makes it look like it should work.

**Comment by ffaubry** [comment]
@stdavis You can reference the path to your locally deployed esri/dojo as:
- absolute: //www.foo.com/path/to/my/local/esri/lib
- relative if your app is deployed in a sub folder: ../.my/local/esri/lib

Or are you talking of using the ember-cli-amd to build the api locally?

**Comment by stdavis** [comment]
It's been too long for me to remember everything that went into this question. But yes, I think that I was interested in using this project to load a locally-built version of the esri api.

**Comment by ffaubry** [comment]
@stdavis If you lib is already prebuilt, then you can use the solutions described above.
This package also supports a way to use the bower esri js-api and build it with the modules used in the ember app.

**Comment by stdavis** [comment]
Good to know. I may try that sometime. Where are the build docs?

**Comment by ggayowsky** [comment]
The application I am currently using is on Ember 3.1, and uses a local instance of the arcgis JS API. It is currently working on v0.4.8, but have tried updating to 1.2.2 without any luck.


Current configuration file looks like this:

```
amd: {
  loader: '/libs/arcgis/init.js',
  packages: [ // user defined AMD packages to search for in application
    'esri', 'dojo', 'dojox', 'dijit', 'put-selector', 'xstyle', 'dgrid'
  ],
  libraryPath: '/libs/arcgis',
  configPath: 'config/dojo-config.js',
  locale: 'en-us'
}
```

And the app failed with the following message:

`GET https://localhost:4200/libs/arcgis/require.js new::ERRABORTED` because the requirejs file isn't there. Do i need to use the libraryPath option to point it at require.js?

**Comment by ffaubry** [comment]
The best way is to host the arcgis lib yourself in your server. This way it's accessible for more than one app.
During development, I install the arcgis lib in my machine somewhere and use http-server to serve it. I point the loader to it and it works.
The last solution is to place the arcgis lib under the public folder. It will be copied in the build folder.
Just be sure that your loader path is correct ('/' in front of the path may take you somewhere else).
Closing for now.
