### ISSUE TITLE
Problem while importing ArcGis library from local

### ISSUE THREAD

**Issue by albertogonper** [Esri/ember-cli-amd#7]
Hello,

First of all, nice work! This is going to be very useful for a lot of people!

I'm going to explain the problem that I encountered while using the library. 

Actually I'm refactoring a project which uses ArcGis library to show a map with some FeatureLayers, the special thing about this project is that it is using an offline plugin to store map parts (basemap tiles and feature layers) on the browser, to achieve this I'm using: [offline-editor-js](https://github.com/Esri/offline-editor-js)

So, I need the Esri library available locally to save it with [HTML5 Application Cache](http://www.w3schools.com/html/html5_app_cache.asp). With the actual code this is working. Now I'm moving to Ember.js

I've downloaded the latest version of ArcGis library from the official website and looking at your code I've achieved to do a setup, but I'm encountering a problem:

![Dojo has.js error (dojo root dir problem)](https://cloud.githubusercontent.com/assets/10727467/10320025/8d9f4960-6c71-11e5-8164-4d2c56151a65.png)

This is my **ember-cli-build.js** file:

![ember-cli-build.js](https://cloud.githubusercontent.com/assets/10727467/10320050/acb6b752-6c71-11e5-9ae0-c425a3993446.png)

I see that the problem is that dojo is not referencing to its root directory, since the **has.js** file is from the Dojo library.

**vendor/arcgis** and **vendor/arcgis/dojo** content:

![vendor/arcgis folder](https://cloud.githubusercontent.com/assets/10727467/10320109/09ee4688-6c72-11e5-9266-5e47c2ed8a5b.png) ![vendor/arcgis/dojo folder](https://cloud.githubusercontent.com/assets/10727467/10320113/10b7e7da-6c72-11e5-808b-b9a59cd93d2d.png)
As you can see **has.js** is inside the dojo folder.

Any idea about how I can fix this?

Thank you,

**Comment by odoe** [comment]
Here is something you can try, but I don't think it's going to give you what you are looking for.

You can try and set up the requireConfig to do what you want.
```javascript
  amdBase: 'bower_components/amdlibrary', // optional - base folder of AMD library
  // RequireJS configuration options
  // Please refere to RequireJS docs for more information
  // http://requirejs.org/docs/optimization.html
  requireConfig: {
    include: [
      'foo/bar/baz'
    ],
    exclude: [
      'lorem/ipsum'
    ],
    paths: {
      'plugins/plugin': 'empty:'
    }
  }
```

Now the bad news. This is really meant to make the add-on universal for other AMD libraries.

The ArcGIS JS API is too extensive to use with ember-cli. The watchers that ember-cli uses will constantly check the folder with the API in it and simply come to a crawl, rendering it unusable.

You could try setting `useRequire` to true. This will inject the `requirejs` loader into the built file for the AMD bits of your code. Then point the paths in the `requireConfig` to the CDN.

```javascript
paths: {
  'esri'        : 'https://js.arcgis.com/3.14/esri',
  'dojo'        : 'https://js.arcgis.com/3.14/dojo',
  'dijit'       : 'https://js.arcgis.com/3.14/dijit',
  'dojox'       : 'https://js.arcgis.com/3.14/dojox',
  'dgrid'       : 'https://js.arcgis.com/3.14/dgrid',
  'put-selector': 'https://js.arcgis.com/3.14/put-selector',
  'xstyle'      : 'https://js.arcgis.com/3.14/xstyle'
}
```

This will kind of work, but you'll probably get some errors due to cross-origin requests. The Dojo loader has methods to handle this, RequireJS does not, or at least not the ones the API is expecting.

I just wanted to provide some options.

**My suggestion, if you want this totally non-CDN:**
Use the addon as normal, using the CDN and without trying to load from a vendor file during development. Then use the [Online JS API Optimizer](http://jso.arcgis.com/) to get a custom build that will work with your app. When you deploy, replace the reference `src` script tag to point to the custom build.

This is the motivating factor behind #4 so that users can use this dependency list for the online optimizer.

I know it's probably not the answer you were hoping for, but I hope that helps.

Thanks.

**Comment by albertogonper** [comment]
Finally the last approach is the only one that worked for me. For now I'll use the CDN, as you said. And when I release the app I'll include an optimized version of the library.

I'm quite interested on #4, this will save me a lot of work :)

Thanks for your help, now I can start refactoring.
